const BASE_URL = process.env.NEXT_APP_BACKEND_URL;

const endpoints = {
  login: "auth/login",
  adminLogin: "admin/login",
  signup: "user/create",
  sendOtp: "auth/send-otp",
  validateOtp: "auth/validate-otp",
  updateUser: "auth/updateClientId",
  updateUserThing: "auth/updateUser",
  viewProfile: "auth/viewProfile",
  feedback: "auth/updateUser",
  iconUpload: "upload",
  saveSetting: "settings",
  lead: "contacts",
  url: "ai/urls",
  addAiActions: "ai/add-ai-actions",
  getActiveChannel: "channel",
  changePassword: "auth/forget-password",
  query: "ai/query",
  fetchSession: "ai/fetch-sessions",
  fetchChatBySession: "ai/fetch-chat-history",
  crawl: "ai/crawl",
  aiActions: "ai-actions",
  persona: "ai/fetch-persona",
  leadEmail: "email/send",
  docUpload: "doc/upload",
  textUpload: "text/plainText",
  deleteSource: "crawlHistory",
  saveCue: "cues",
  allLeads: "contacts/allLeads",
  chatInsight: "ai/chatInsights",
  saveAppointment: "schedule",
  bookSlot: "book-slot",
  saveChatByAppointment: "crawlHistory/saveAppointmentChat",
  getAppointment: "book-slot",
  appointmentSendEmail: "email/send",
  saveTicket: "ticket",
  saveTicketComment: "ticket/comment",
  updateChatHistory: "chatHistory",
  saveAddress: "chat-location",
  newProject: "project",
  getSuccessUrl: "source/getSuccessUrls",
  getSkipUrls: "source/getSkipUrls",
  intentPercentage: "chat-insight/intent-percentages",
  countryData: "chat-location/getCountryData",
  copilotActions: "chatHistory/copilot-data",
  graphChatInsights: "chat-insight/word-cloud",
  getDocs: "source/getDocs",
  getAllSuccessUrls: "source/getAllSuccessUrls",
  getAllFailUrls: "source/getAllFailUrls",
  savePersona: "persona",
  getAllFiles: "source/getAllDocs",
  getLocation: "auth/getLocation",
  getQueryData: "project/sdk",
  dashboardData: "chatHistory/dashboard-data",
  dashboardMessageCount: "chatHistory/dashboard-message-count",
  generatePlugin: "generatePlugin",
  characterCount: "project/characterCount",
  instantRetrain: "ai/instantRetrain",
  saveInstantRetrainText: "instantRetrainLogs",
  getPaginatedText: "instantRetrainLogs/getPaginatedText",
  getTextList: "source/getTextList",
  deleteTrainedText: "crawlHistory/deleteText",
  saveTrainedText: "source/save-source-text",
  getAPIToken: "auth/getAPIForVoip",
  saveChatInsightsBySessionId: "ai/chatInsightsBySessionId",
  subscriptionPlanDetails: "subscription/subscriptionDetail",
  getActivePlanDetails: "subscription/activePlanDetail",
  updateTotalCharactersTrainedOnCrawlActivePlan:
    "subscription/updateTotalCharacterCountOnCrawl",
  allCharacterCount: "organisation/characterCount",
  validateJWT: "auth/validate-token",
  saveDetails: "webhook/save-data",
  getAdditionUrls: "source/getAdditionUrls",
  chatStream: BASE_URL + "ai/streamQuery",
  fetchSessionConversation: "chatHistory/fetch-sessions",
  getClientIdbyUserId: "source/getClientIdbyUserId",
  exportConversation: "chatHistory/export-conversation",
  getCountryList: "chat-location/countries",
  getPhoneIdWabaId: "webhook/getPhoneDetails",
  voice: "voice-chat",
  uploadWhatsapp: "webhook/upload-whatsapp",
  getSpeechToken: "speech-token",
  storeVoiceConverstation: "voice-conversation",
};

export default endpoints;
